import keyMirror from 'keymirror';

export default keyMirror({
    LOAD_CATEGORIES_REQUEST: null,
    LOAD_CATEGORIES_SUCCESS: null,
    LOAD_CATEGORIES_FAIL: null,
    LOAD_TASKS_REQUEST: null,
    LOAD_TASKS_SUCCESS: null,
    LOAD_TASKS_FAIL: null,
    LOAD_PRIORITIES_REQUEST: null,
    LOAD_PRIORITIES_SUCCESS: null,
    LOAD_PRIORITIES_FAIL: null,
    DELETE_CATEGORIES_REQUEST: null,
    DELETE_CATEGORIES_SUCCESS: null,
    DELETE_CATEGORIES_FAIL: null,
    CREATE_TASK_SUCCESS: null
});
